### PR TITLE
Simplify Bytes.toString implementation

### PR DESCRIPTION
**Pull request by carterkozak**

### CODE REVIEW

**Comment by markelliot** [comment]
the original implementation matches the style of the beans we generate

**Comment by carterkozak** [comment]
I don't believe they use `.class.getSimpleName()`. They also memoize hashcode values, but I wouldn't recommend doing that here.

**Comment by markelliot** [comment]
would be fine to remove the .getSimpleName() stuff in favor of hard-coding `"Bytes"` but prefer we match the style of the codebase.

**Comment by carterkozak** [comment]
Updated

**Review by markelliot — APPROVED** [review]

**Pull request merged**
