### PR TITLE
use ExternalLoggingFactory on DropwizardAppExtension

### PR DESCRIPTION
**Pull request by bjlaub**
## Before this PR
Dropwizard's `DefaultLoggingFactory` always resets the root logging level to `DEBUG` via the `reset()` method, which is invoked via `DropwizardTestSupport`. Unfortunately due to https://issues.apache.org/jira/browse/HTTPCLIENT-2313 this can cause other test classes to fail if they run after `JerseyServiceEteTest`. To work around that, just use `ExternalLoggingFactory` which is more representative of real-world environments anyway.

## After this PR

==COMMIT_MSG==
use ExternalLoggingFactory on DropwizardAppExtension
==COMMIT_MSG==

## Possible downsides?
Some tests no longer pass. I'm deleting them since I think they're inconsequential.

### CODE REVIEW

**Review by carterkozak — DISMISSED** [review]

**Comment by carterkozak** [comment]
👍

**Review by bmarcaur — DISMISSED** [review]

**Comment by carterkozak** [comment]
Tests are failing with:
```
Caused by: org.gradle.api.GradleException: Found 1 implicit dependencies - consider adding the following explicit dependencies to 'conjure-java-core/build.gradle', or avoid using classes from these jars:
    dependencies {
        testImplementation 'io.dropwizard:dropwizard-logging'
    }
 ```

**Comment by carterkozak** [comment]
👍

**Comment by felixdesouza** [comment]
👍

**Review by bmarcaur — APPROVED** [review]

**Pull request merged**
