### PR TITLE
Upgrade guava dependency to 27.0.1-jre (was 23.6.1-jre)

### PR DESCRIPTION
**Pull request by carterkozak**

### CODE REVIEW

**Comment by iamdanfox** [comment]
Surprising this hasn't affected anything in the locks.. are we upgrading this just for tests?

**Comment by iamdanfox** [comment]
:+1:

**Comment by carterkozak** [comment]
Actually, this version is already present in the lockfile, I can't imagine that's what we expect

**Comment by iamdanfox** [comment]
```
./gradlew why --hash 52684e1d

> Task :why
com.google.guava:guava:27.0.1-jre
        projects -> 23.6.1-jre
        com.fasterxml.jackson.datatype:jackson-datatype-guava -> 18.0
        com.google.googlejavaformat:google-java-format -> 27.0.1-jre
        com.palantir.conjure:conjure-generator-common -> 23.6.1-jre
        com.palantir.syntactic-paths:syntactic-paths -> 18.0
        com.palantir.tracing:tracing -> 23.6.1-jre

```

**Pull request merged**
