### PR TITLE
Add the 'Undertow: ' prefix to conjure-undertow tracing spans

### PR DESCRIPTION
**Pull request by carterkozak**
For additional context see:
https://github.com/palantir/tracing-java/pull/58

### CODE REVIEW

**Comment by rubenfiszel** [comment]
Typo in PR name.
If we go that route, we might me interested to also insert the Server library version

**Comment by carterkozak** [comment]
Woops, fixed the typo. I want to keep parity with tracing-java for the time being

**Comment by markelliot** [comment]
It would be slightly better decomp if this tracing handler lived with all the other tracing handlers so that we could keep the tracing concern in sync.

**Comment by carterkozak** [comment]
Sure, now that this generator is stable we can split out the TraceHandler into the tracing project.

**Comment by carterkozak** [comment]
https://github.com/palantir/tracing-java/pull/60

**Pull request closed without merging**
